name: Check2

on:
  pull_request:
    branches: [ master ]

jobs:
  check1:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Check
      run: |
        ./check 2
